### ISSUE TITLE
Allow options for badge sizing

### ISSUE THREAD

**Issue by yubinjodev** [mattrltrent/stackoverflow_badge#3]
I actually love the design, I think I'll love it even more if I can customize the size of the badge.

**Comment by mattrltrent** [comment]
Working on updating it right now just for you, @yubinjodev! 🫡

**Comment by mattrltrent** [comment]
New version is live. You can see the changes in the `README.md` for a full breakdown, or, for the TLDR, just append `&mini=true` to the end of the URL and it should display a small and simple badge for you.

Let me know if it works! @yubinjodev

**Comment by mattrltrent** [comment]
@yubinjodev 

Mini badge has since been improved. You can see what it looks like on my personal GitHub profile. Perhaps this works better for you.
